language: php

php:
  - 5.6
  - 7.0
  - 7.1

sudo: false

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - ./vendor/bin/phpunit

matrix:
  allow_failures:
    - php: 7.1
  fast_finish: true